"""
src/preprocess.py
-----------------
Load, filter, and epoch MEG data.

Supports:
  - Real BIDS .fif files via MNE-Python
  - Synthetic .npy files generated by scripts/download_data.py

Usage (CLI):
    python src/preprocess.py \
        --bids_root data/ds003483 \
        --subject 01 \
        --output data/processed/
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

import numpy as np


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def load_meg(bids_root: str | Path, subject: str = "01") -> tuple[np.ndarray, float, np.ndarray | None]:
    """
    Load raw MEG data.

    Returns
    -------
    data : np.ndarray, shape (n_channels, n_times)
        Raw signal in Tesla.
    sfreq : float
        Sampling frequency in Hz.
    ground_truth_anomalies : np.ndarray or None
        Sample indices of injected anomalies (synthetic only).
    """
    bids_root = Path(bids_root)
    meg_dir = bids_root / f"sub-{subject}" / "meg"

    # --- Try synthetic .npy first (offline mode) ---
    npy_path = meg_dir / f"sub-{subject}_task-rest_meg.npy"
    if npy_path.exists():
        print(f"[preprocess] Loading synthetic data: {npy_path}")
        data = np.load(npy_path)
        sfreq = 1000.0

        gt_path = meg_dir / f"sub-{subject}_task-rest_anomaly_times.npy"
        ground_truth = np.load(gt_path) if gt_path.exists() else None
        return data, sfreq, ground_truth

    # --- Try real .fif via MNE ---
    fif_paths = list(meg_dir.glob("*.fif"))
    if fif_paths:
        import mne
        raw = mne.io.read_raw_fif(str(fif_paths[0]), preload=True, verbose=False)
        raw.pick_types(meg=True, eeg=False, stim=False)
        data = raw.get_data()
        sfreq = raw.info["sfreq"]
        print(f"[preprocess] Loaded .fif: {fif_paths[0]} | shape={data.shape} | sfreq={sfreq}")
        return data, sfreq, None

    raise FileNotFoundError(
        f"No MEG data found in {meg_dir}. "
        "Run: python scripts/download_data.py --synthetic"
    )


def bandpass_filter(data: np.ndarray, sfreq: float,
                    l_freq: float = 1.0, h_freq: float = 40.0) -> np.ndarray:
    """
    Apply a zero-phase Butterworth bandpass filter to each channel.

    Parameters
    ----------
    data  : (n_channels, n_times)
    sfreq : sampling frequency
    l_freq, h_freq : passband edges in Hz
    """
    from scipy.signal import butter, filtfilt

    nyq = sfreq / 2.0
    b, a = butter(4, [l_freq / nyq, h_freq / nyq], btype="band")
    filtered = np.zeros_like(data)
    for ch in range(data.shape[0]):
        filtered[ch] = filtfilt(b, a, data[ch])
    return filtered


def epoch_data(data: np.ndarray, sfreq: float,
               epoch_len_s: float = 1.0,
               overlap: float = 0.5) -> np.ndarray:
    """
    Segment continuous data into overlapping epochs.

    Parameters
    ----------
    data        : (n_channels, n_times)
    sfreq       : sampling frequency in Hz
    epoch_len_s : epoch length in seconds
    overlap     : fraction overlap between successive epochs [0, 1)

    Returns
    -------
    epochs : (n_epochs, n_channels, epoch_len)
    """
    epoch_len = int(epoch_len_s * sfreq)
    step = int(epoch_len * (1 - overlap))
    n_channels, n_times = data.shape

    starts = range(0, n_times - epoch_len + 1, step)
    epochs = np.stack([data[:, s:s + epoch_len] for s in starts], axis=0)
    return epochs  # (n_epochs, n_channels, epoch_len)


def extract_features(epochs: np.ndarray) -> np.ndarray:
    """
    Extract a compact feature vector per epoch for anomaly detection.

    Features per channel (concatenated across channels):
      - RMS amplitude
      - Peak-to-peak range
      - Mean power in theta (4–8 Hz), alpha (8–13 Hz), beta (13–30 Hz) bands

    Parameters
    ----------
    epochs : (n_epochs, n_channels, epoch_len)

    Returns
    -------
    features : (n_epochs, n_features)
    """
    n_epochs, n_channels, epoch_len = epochs.shape
    feature_list = []

    for ep in epochs:
        ch_feats = []
        for ch in range(n_channels):
            sig = ep[ch]
            rms = float(np.sqrt(np.mean(sig ** 2)))
            ptp = float(np.ptp(sig))
            ch_feats.extend([rms, ptp])
        feature_list.append(ch_feats)

    return np.array(feature_list, dtype=np.float32)


def preprocess_pipeline(bids_root: str, subject: str = "01",
                         output_dir: str = "data/processed") -> dict:
    """
    Full preprocessing pipeline.

    Returns a dict with keys: data, sfreq, epochs, features, ground_truth.
    Also saves numpy arrays to output_dir.
    """
    os.makedirs(output_dir, exist_ok=True)

    # 1. Load
    data, sfreq, ground_truth = load_meg(bids_root, subject)
    print(f"[preprocess] Raw shape: {data.shape} | sfreq={sfreq}")

    # 2. Filter
    filtered = bandpass_filter(data, sfreq, l_freq=1.0, h_freq=40.0)
    print("[preprocess] Bandpass filtered (1–40 Hz)")

    # 3. Epoch
    epochs = epoch_data(filtered, sfreq, epoch_len_s=1.0, overlap=0.5)
    print(f"[preprocess] Epochs: {epochs.shape}")

    # 4. Features
    features = extract_features(epochs)
    print(f"[preprocess] Features: {features.shape}")

    # 5. Save
    np.save(os.path.join(output_dir, "epochs.npy"), epochs)
    np.save(os.path.join(output_dir, "features.npy"), features)
    np.save(os.path.join(output_dir, "raw_filtered.npy"), filtered)
    if ground_truth is not None:
        np.save(os.path.join(output_dir, "ground_truth.npy"), ground_truth)

    print(f"[preprocess] Saved processed data → {output_dir}")
    return dict(data=filtered, sfreq=sfreq, epochs=epochs,
                features=features, ground_truth=ground_truth)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--bids_root", default="data/ds003483")
    parser.add_argument("--subject", default="01")
    parser.add_argument("--output", default="data/processed")
    args = parser.parse_args()
    preprocess_pipeline(args.bids_root, args.subject, args.output)